repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.min\.(js|css)$'
      - id: end-of-file-fixer
        exclude: '\.min\.(js|css)$'
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
        args: ['--maxkb=2048']

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^backend/
        args: ['--line-length=120']

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^backend/
        args: ['--profile', 'black', '--line-length=120']

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^backend/app/
        args: ['--max-line-length=120', '--extend-ignore=E203,E501,W503,F401,F841']
