import React, { useState, useEffect } from 'react';
import { api } from '../../services/api';
import { PortalLayout } from '../../components/layout/PortalLayout';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import {
  BookOpen,
  Plus,
  Sparkles,
  Users,
  Award,
  CheckCircle2,
  Clock,
  Send,
  Trash2,
  Edit,
  Search,
  ExternalLink,
  ShieldCheck,
  GraduationCap,
  X,
  Layers,
  ChevronRight,
  Mail,
  Zap
} from 'lucide-react';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { CertificateModal } from '../../components/common/CertificateModal';

export function IndustryLearningPage() {
  const { user } = useAuth();
  const toast = useToast();

  const [programs, setPrograms] = useState([]);
  const [loading, setLoading] = useState(true);

  // Publish / Edit Modal
  const [showPublishModal, setShowPublishModal] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editId, setEditId] = useState(null);

  // AI Generator state
  const [aiTopic, setAiTopic] = useState('');
  const [generatingAi, setGeneratingAi] = useState(false);

  // Form Fields
  const [title, setTitle] = useState('');
  const [providerName, setProviderName] = useState(user?.organization_name || user?.username || 'Cognizant IT Services');
  const [programType, setProgramType] = useState('course');
  const [learningMode, setLearningMode] = useState('self_paced');
  const [duration, setDuration] = useState('4 Weeks');
  const [skillsCovered, setSkillsCovered] = useState('');
  const [description, setDescription] = useState('');
  const [eligibility, setEligibility] = useState('');
  const [externalLink, setExternalLink] = useState('');
  const [feeAmount, setFeeAmount] = useState(0);
  const [autoCertify, setAutoCertify] = useState(true);
  const [modules, setModules] = useState([
    { id: 1, title: 'Module 1: Orientation & Foundations', duration: '2 Hours', description: 'Core principles and setup.' },
    { id: 2, title: 'Module 2: Practical Implementation Workflows', duration: '3 Hours', description: 'Hands-on architectural patterns.' },
    { id: 3, title: 'Module 3: Enterprise Best Practices & Security', duration: '2.5 Hours', description: 'Performance and production standards.' },
    { id: 4, title: 'Module 4: Capstone Evaluation & Certification', duration: '2 Hours', description: 'Practical milestone for credentialing.' },
  ]);
  const [submitting, setSubmitting] = useState(false);

  // Enrolled Roster Modal
  const [showRosterModal, setShowRosterModal] = useState(false);
  const [activeProgram, setActiveProgram] = useState(null);
  const [roster, setRoster] = useState([]);
  const [loadingRoster, setLoadingRoster] = useState(false);
  const [issuingCertId, setIssuingCertId] = useState(null);

  // Certificate Modal Preview
  const [previewCert, setPreviewCert] = useState(null);

  useEffect(() => {
    fetchPrograms();
  }, []);

  const fetchPrograms = () => {
    setLoading(true);
    api.get('/learning-programs/industry/manage')
      .then((data) => setPrograms(data))
      .catch((err) => toast.error('Error fetching programs: ' + err.message))
      .finally(() => setLoading(false));
  };

  const handleAiGenerate = async () => {
    if (!aiTopic.trim()) {
      toast.error('Please enter a course topic or skill for AI generation.');
      return;
    }

    setGeneratingAi(true);
    try {
      const res = await api.post('/learning-programs/ai-generate-syllabus', {
        topic: aiTopic,
        program_type: programType,
        duration: duration,
        skill_level: 'Intermediate',
      });

      if (res.title) setTitle(res.title);
      if (res.description) setDescription(res.description);
      if (res.skills_covered) setSkillsCovered(res.skills_covered);
      if (res.duration) setDuration(res.duration);
      if (res.eligibility) setEligibility(res.eligibility);
      if (res.modules && Array.isArray(res.modules)) {
        setModules(res.modules);
      }
      toast.success('Curriculum and modules generated by AI!');
    } catch (err) {
      toast.error('AI generation error: ' + err.message);
    } finally {
      setGeneratingAi(false);
    }
  };

  const handleOpenPublish = (progToEdit = null) => {
    if (progToEdit) {
      setIsEditing(true);
      setEditId(progToEdit.id);
      setTitle(progToEdit.title);
      setProviderName(progToEdit.provider_name);
      setProgramType(progToEdit.program_type);
      setLearningMode(progToEdit.learning_mode);
      setDuration(progToEdit.duration || '4 Weeks');
      setSkillsCovered(progToEdit.skills_covered || '');
      setDescription(progToEdit.description || '');
      setEligibility(progToEdit.eligibility || '');
      setExternalLink(progToEdit.external_link || '');
      setFeeAmount(progToEdit.fee_amount || 0);
      setAutoCertify(progToEdit.auto_certify ?? true);
      try {
        setModules(JSON.parse(progToEdit.modules_json || '[]'));
      } catch {
        setModules([]);
      }
    } else {
      setIsEditing(false);
      setEditId(null);
      setTitle('');
      setAiTopic('');
      setProviderName(user?.organization_name || user?.username || 'Cognizant IT Services');
      setProgramType('course');
      setLearningMode('self_paced');
      setDuration('4 Weeks');
      setSkillsCovered('Full-Stack Development, React, Node.js, REST API');
      setDescription('');
      setEligibility('Basic programming knowledge');
      setExternalLink('');
      setFeeAmount(0);
      setAutoCertify(true);
      setModules([
        { id: 1, title: 'Module 1: Orientation & Foundations', duration: '2 Hours', description: 'Core principles and setup.' },
        { id: 2, title: 'Module 2: Practical Implementation Workflows', duration: '3 Hours', description: 'Hands-on architectural patterns.' },
        { id: 3, title: 'Module 3: Enterprise Best Practices & Security', duration: '2.5 Hours', description: 'Performance and production standards.' },
        { id: 4, title: 'Module 4: Capstone Evaluation & Certification', duration: '2 Hours', description: 'Practical milestone for credentialing.' },
      ]);
    }
    setShowPublishModal(true);
  };

  const handleSaveProgram = async (e) => {
    e.preventDefault();
    if (!title.trim() || !description.trim()) {
      toast.error('Title and description are required.');
      return;
    }

    setSubmitting(true);
    const payload = {
      title,
      provider_name: providerName || 'Enterprise Partner',
      provider_type: 'industry',
      program_type: programType,
      learning_mode: learningMode,
      duration,
      skills_covered: skillsCovered,
      description,
      eligibility,
      external_link: externalLink || null,
      fee_amount: parseFloat(feeAmount) || 0,
      auto_certify: autoCertify,
      modules_json: JSON.stringify(modules),
    };

    try {
      if (isEditing && editId) {
        await api.put(`/learning-programs/${editId}`, payload);
        toast.success('Training program updated successfully.');
      } else {
        await api.post('/learning-programs', payload);
        toast.success('Training program published to National E-Learning Catalog!');
      }
      setShowPublishModal(false);
      fetchPrograms();
    } catch (err) {
      toast.error('Error saving program: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeleteProgram = async (id) => {
    if (!window.confirm('Are you sure you want to delete this learning program? All associated enrollments will be deleted.')) {
      return;
    }
    try {
      await api.delete(`/learning-programs/${id}`);
      toast.success('Program removed.');
      fetchPrograms();
    } catch (err) {
      toast.error('Error: ' + err.message);
    }
  };

  const handleOpenRoster = async (prog) => {
    setActiveProgram(prog);
    setShowRosterModal(true);
    setLoadingRoster(true);
    try {
      const data = await api.get(`/learning-programs/${prog.id}/students`);
      setRoster(data);
    } catch (err) {
      toast.error('Error loading participant roster: ' + err.message);
    } finally {
      setLoadingRoster(false);
    }
  };

  const handleIssueCertificate = async (enrollmentId) => {
    setIssuingCertId(enrollmentId);
    try {
      const cert = await api.post(`/learning-programs/enrollments/${enrollmentId}/issue-certificate`);
      toast.success(`Verified Certificate #${cert.certificate_number} issued and emailed to student!`);
      // Refresh roster
      if (activeProgram) {
        const updated = await api.get(`/learning-programs/${activeProgram.id}/students`);
        setRoster(updated);
      }
      fetchPrograms();
    } catch (err) {
      toast.error('Error issuing certificate: ' + err.message);
    } finally {
      setIssuingCertId(null);
    }
  };

  // Metrics summary
  const totalPrograms = programs.length;
  const totalEnrollments = programs.reduce((acc, p) => acc + (p.enrollments_count || 0), 0);
  const totalCompletions = programs.reduce((acc, p) => acc + (p.completed_count || 0), 0);
  const completionRate = totalEnrollments > 0 ? Math.round((totalCompletions / totalEnrollments) * 100) : 0;

  return (
    <PortalLayout title="Industry Academy & Training Programs" allowedRoles={['industry', 'institution', 'admin']}>
      {/* ─── Hero Overview Banner ─── */}
      <div
        style={{
          background: 'linear-gradient(135deg, #1E293B 0%, #0F172A 100%)',
          borderRadius: '16px',
          padding: '28px 32px',
          color: '#FFFFFF',
          marginBottom: '24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '20px',
          boxShadow: '0 10px 25px -5px rgba(15, 23, 42, 0.3)',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        <div style={{ position: 'relative', zIndex: 1, maxWidth: '600px' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: 'rgba(56, 189, 248, 0.15)', padding: '4px 12px', borderRadius: '20px', color: '#38BDF8', fontSize: '12px', fontWeight: 700, marginBottom: '10px' }}>
            <Sparkles size={14} /> AI-POWERED E-LEARNING & CERTIFICATION ENGINE
          </div>
          <h2 style={{ fontSize: '24px', fontWeight: 800, margin: '0 0 6px 0', letterSpacing: '-0.3px', color: '#FFFFFF' }}>
            Publish Courses, Certifications & Workshops
          </h2>
          <p style={{ fontSize: '13.5px', color: '#94A3B8', margin: 0, lineHeight: 1.5 }}>
            Empower colleges and students with enterprise-standard training cohorts. Certificates are cryptographically generated and automatically emailed to students upon completion.
          </p>
        </div>

        <button
          onClick={() => handleOpenPublish()}
          style={{
            position: 'relative',
            zIndex: 1,
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
            backgroundColor: '#2563EB',
            color: '#FFFFFF',
            border: 'none',
            borderRadius: '10px',
            padding: '12px 22px',
            fontSize: '14px',
            fontWeight: 700,
            cursor: 'pointer',
            boxShadow: '0 4px 14px rgba(37, 99, 235, 0.4)',
            transition: 'transform 0.15s, background-color 0.15s',
          }}
          onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#1D4ED8')}
          onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = '#2563EB')}
        >
          <Plus size={16} /> Publish New Program
        </button>
      </div>

      {/* ─── Metric Cards Grid ─── */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
          gap: '16px',
          marginBottom: '24px',
        }}
      >
        <div className="card" style={{ padding: '18px 20px', display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{ width: '46px', height: '46px', borderRadius: '12px', backgroundColor: '#EFF6FF', color: '#2563EB', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <BookOpen size={22} />
          </div>
          <div>
            <div style={{ fontSize: '12px', color: '#64748B', fontWeight: 600 }}>Active Programs</div>
            <div style={{ fontSize: '22px', fontWeight: 800, color: '#0F172A', marginTop: '2px' }}>{totalPrograms}</div>
          </div>
        </div>

        <div className="card" style={{ padding: '18px 20px', display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{ width: '46px', height: '46px', borderRadius: '12px', backgroundColor: '#F0FDF4', color: '#16A34A', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Users size={22} />
          </div>
          <div>
            <div style={{ fontSize: '12px', color: '#64748B', fontWeight: 600 }}>Enrolled Learners</div>
            <div style={{ fontSize: '22px', fontWeight: 800, color: '#0F172A', marginTop: '2px' }}>{totalEnrollments}</div>
          </div>
        </div>

        <div className="card" style={{ padding: '18px 20px', display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{ width: '46px', height: '46px', borderRadius: '12px', backgroundColor: '#FEF3C7', color: '#D97706', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Award size={22} />
          </div>
          <div>
            <div style={{ fontSize: '12px', color: '#64748B', fontWeight: 600 }}>Certificates Issued</div>
            <div style={{ fontSize: '22px', fontWeight: 800, color: '#0F172A', marginTop: '2px' }}>{totalCompletions}</div>
          </div>
        </div>

        <div className="card" style={{ padding: '18px 20px', display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{ width: '46px', height: '46px', borderRadius: '12px', backgroundColor: '#FAF5FF', color: '#9333EA', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <CheckCircle2 size={22} />
          </div>
          <div>
            <div style={{ fontSize: '12px', color: '#64748B', fontWeight: 600 }}>Completion Rate</div>
            <div style={{ fontSize: '22px', fontWeight: 800, color: '#0F172A', marginTop: '2px' }}>{completionRate}%</div>
          </div>
        </div>
      </div>

      {/* ─── Published Programs Catalog Table ─── */}
      <div className="card">
        <div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h3 className="card-title" style={{ margin: 0 }}>Published Training Initiatives</h3>
            <p className="text-muted" style={{ fontSize: '12px', margin: '3px 0 0' }}>
              Manage curriculum syllabus, participant cohorts, and automated certificate dispatching
            </p>
          </div>
        </div>

        {loading ? (
          <LoadingSpinner message="Loading training initiatives..." />
        ) : programs.length === 0 ? (
          <div style={{ padding: '48px 24px', textAlign: 'center' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '50%', backgroundColor: '#EFF6FF', color: '#2563EB', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
              <BookOpen size={26} />
            </div>
            <h4 style={{ fontSize: '16px', fontWeight: 700, color: '#0F172A', margin: '0 0 6px' }}>No training programs published yet</h4>
            <p style={{ fontSize: '13px', color: '#64748B', maxWidth: '420px', margin: '0 auto 20px' }}>
              Publish your first certification course or workshop. AI can draft the complete syllabus and module breakdown in seconds.
            </p>
            <button onClick={() => handleOpenPublish()} className="btn btn-primary btn-sm">
              <Plus size={14} /> Publish First Program
            </button>
          </div>
        ) : (
          <div className="table-responsive">
            <table className="table">
              <thead>
                <tr>
                  <th>Program Title & Details</th>
                  <th>Type & Mode</th>
                  <th>Duration</th>
                  <th>Enrollments</th>
                  <th>Auto-Certify</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {programs.map((p) => (
                  <tr key={p.id}>
                    <td>
                      <div style={{ fontWeight: 700, color: '#0F172A', fontSize: '14px' }}>{p.title}</div>
                      <div style={{ fontSize: '12px', color: '#64748B', marginTop: '2px' }}>
                        {p.skills_covered ? `Skills: ${p.skills_covered}` : p.provider_name}
                      </div>
                    </td>
                    <td>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', alignItems: 'flex-start' }}>
                        <span className="badge badge-primary" style={{ textTransform: 'capitalize' }}>
                          {p.program_type}
                        </span>
                        <span style={{ fontSize: '11px', color: '#64748B', textTransform: 'capitalize' }}>
                          {p.learning_mode.replace('_', ' ')}
                        </span>
                      </div>
                    </td>
                    <td style={{ fontSize: '13px', color: '#334155' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
                        <Clock size={13} color="#64748B" /> {p.duration || 'Self-Paced'}
                      </div>
                    </td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <span style={{ fontWeight: 700, fontSize: '14px', color: '#0F172A' }}>
                          {p.enrollments_count || 0}
                        </span>
                        <span style={{ fontSize: '11.5px', color: '#059669', fontWeight: 600 }}>
                          ({p.completed_count || 0} Certified)
                        </span>
                      </div>
                    </td>
                    <td>
                      <span
                        style={{
                          display: 'inline-flex',
                          alignItems: 'center',
                          gap: '4px',
                          fontSize: '11.5px',
                          fontWeight: 700,
                          padding: '3px 8px',
                          borderRadius: '6px',
                          backgroundColor: p.auto_certify ? '#ECFDF5' : '#F1F5F9',
                          color: p.auto_certify ? '#047857' : '#64748B',
                        }}
                      >
                        {p.auto_certify ? <Zap size={12} /> : <Clock size={12} />}
                        {p.auto_certify ? 'Automatic' : 'Manual'}
                      </span>
                    </td>
                    <td style={{ textAlign: 'right' }}>
                      <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
                        <button
                          onClick={() => handleOpenRoster(p)}
                          className="btn btn-secondary btn-sm"
                          style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '12px' }}
                          title="View Enrolled Students"
                        >
                          <Users size={13} /> Cohort ({p.enrollments_count || 0})
                        </button>
                        <button
                          onClick={() => handleOpenPublish(p)}
                          className="btn btn-outline btn-sm"
                          style={{ padding: '6px 8px' }}
                          title="Edit Program"
                        >
                          <Edit size={13} />
                        </button>
                        <button
                          onClick={() => handleDeleteProgram(p.id)}
                          className="btn btn-outline btn-sm"
                          style={{ padding: '6px 8px', color: '#EF4444', borderColor: '#FCA5A5' }}
                          title="Delete Program"
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ─── Publish / Edit Program Modal with AI Generator ─── */}
      {showPublishModal && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            backgroundColor: 'rgba(15, 23, 42, 0.65)',
            backdropFilter: 'blur(5px)',
            zIndex: 9999,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px',
            overflowY: 'auto',
          }}
          onClick={(e) => {
            if (e.target === e.currentTarget) setShowPublishModal(false);
          }}
        >
          <div
            style={{
              backgroundColor: '#FFFFFF',
              borderRadius: '16px',
              width: '100%',
              maxWidth: '740px',
              maxHeight: '90vh',
              boxShadow: '0 25px 60px -15px rgba(0, 0, 0, 0.3)',
              overflow: 'hidden',
              display: 'flex',
              flexDirection: 'column',
            }}
          >
            {/* Modal Header */}
            <div
              style={{
                padding: '20px 24px',
                background: 'linear-gradient(90deg, #EFF6FF 0%, #DBEAFE 100%)',
                borderBottom: '1px solid #BFDBFE',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', backgroundColor: '#2563EB', color: '#FFFFFF', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <BookOpen size={20} />
                </div>
                <div>
                  <h3 style={{ margin: 0, fontSize: '17px', fontWeight: 800, color: '#0F172A' }}>
                    {isEditing ? 'Edit Training Program' : 'Publish New Training Program'}
                  </h3>
                  <p style={{ margin: '2px 0 0', fontSize: '12.5px', color: '#475569' }}>
                    Setup curriculum modules and automated certificate parameters
                  </p>
                </div>
              </div>
              <button
                onClick={() => setShowPublishModal(false)}
                style={{ background: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}
              >
                <X size={16} />
              </button>
            </div>

            {/* Modal Form */}
            <form onSubmit={handleSaveProgram} style={{ padding: '24px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '18px' }}>

              {/* AI Quick Generator Box */}
              {!isEditing && (
                <div
                  style={{
                    backgroundColor: '#F0FDF4',
                    border: '1.5px solid #86EFAC',
                    borderRadius: '12px',
                    padding: '16px',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#166534', fontWeight: 700, fontSize: '13px', marginBottom: '8px' }}>
                    <Sparkles size={16} /> Instant AI Syllabus Generator
                  </div>
                  <div style={{ display: 'flex', gap: '10px' }}>
                    <input
                      type="text"
                      placeholder="e.g. Full-Stack React & FastAPI, AWS Cloud Engineering, GenAI Prompting"
                      value={aiTopic}
                      onChange={(e) => setAiTopic(e.target.value)}
                      style={{
                        flex: 1,
                        padding: '9px 12px',
                        borderRadius: '8px',
                        border: '1px solid #CBD5E1',
                        fontSize: '13.5px',
                        backgroundColor: '#FFFFFF',
                      }}
                    />
                    <button
                      type="button"
                      onClick={handleAiGenerate}
                      disabled={generatingAi}
                      style={{
                        padding: '9px 18px',
                        borderRadius: '8px',
                        border: 'none',
                        backgroundColor: '#16A34A',
                        color: '#FFFFFF',
                        fontWeight: 700,
                        fontSize: '13px',
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '6px',
                        cursor: generatingAi ? 'not-allowed' : 'pointer',
                      }}
                    >
                      {generatingAi ? <LoadingSpinner inline size={14} /> : <Sparkles size={14} />}
                      {generatingAi ? 'Drafting...' : 'Generate with AI'}
                    </button>
                  </div>
                </div>
              )}

              {/* Title */}
              <div>
                <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#1E293B', marginBottom: '6px' }}>
                  Program Title <span style={{ color: '#EF4444' }}>*</span>
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Enterprise Full-Stack Engineering Certification"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #CBD5E1', fontSize: '13.5px', boxSizing: 'border-box' }}
                />
              </div>

              {/* Two Column Row: Program Type & Learning Mode */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#1E293B', marginBottom: '6px' }}>
                    Program Nature <span style={{ color: '#EF4444' }}>*</span>
                  </label>
                  <select
                    value={programType}
                    onChange={(e) => setProgramType(e.target.value)}
                    style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #CBD5E1', fontSize: '13.5px', backgroundColor: '#FFFFFF', boxSizing: 'border-box' }}
                  >
                    <option value="course">Certification Course</option>
                    <option value="bootcamp">Intensive Bootcamp</option>
                    <option value="workshop">Hands-on Technical Workshop</option>
                    <option value="mentorship">Live Industry Mentorship Cohort</option>
                    <option value="fdp">Faculty Development Program (FDP)</option>
                  </select>
                </div>

                <div>
                  <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#1E293B', marginBottom: '6px' }}>
                    Delivery Mode <span style={{ color: '#EF4444' }}>*</span>
                  </label>
                  <select
                    value={learningMode}
                    onChange={(e) => setLearningMode(e.target.value)}
                    style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #CBD5E1', fontSize: '13.5px', backgroundColor: '#FFFFFF', boxSizing: 'border-box' }}
                  >
                    <option value="self_paced">Self-Paced Online (Interactive Modules)</option>
                    <option value="online">Live Online Instructor-led</option>
                    <option value="hybrid">Hybrid (Campus + Online)</option>
                    <option value="offline">On-Campus / Corporate Lab</option>
                  </select>
                </div>
              </div>

              {/* Two Column Row: Duration & Skills Covered */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#1E293B', marginBottom: '6px' }}>
                    Estimated Duration
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. 4 Weeks, 30 Hours"
                    value={duration}
                    onChange={(e) => setDuration(e.target.value)}
                    style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #CBD5E1', fontSize: '13.5px', boxSizing: 'border-box' }}
                  />
                </div>

                <div>
                  <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#1E293B', marginBottom: '6px' }}>
                    Skills Covered (Comma-Separated)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. React, Node.js, REST API, Docker"
                    value={skillsCovered}
                    onChange={(e) => setSkillsCovered(e.target.value)}
                    style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #CBD5E1', fontSize: '13.5px', boxSizing: 'border-box' }}
                  />
                </div>
              </div>

              {/* Description */}
              <div>
                <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#1E293B', marginBottom: '6px' }}>
                  Overview & Learning Objectives <span style={{ color: '#EF4444' }}>*</span>
                </label>
                <textarea
                  rows={3}
                  required
                  placeholder="Detail the course outcomes, practical competencies, and target audience..."
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #CBD5E1', fontSize: '13.5px', fontFamily: 'inherit', boxSizing: 'border-box' }}
                />
              </div>

              {/* Modules Breakdown Section */}
              <div style={{ border: '1px solid #E2E8F0', borderRadius: '10px', padding: '16px', backgroundColor: '#F8FAFC' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                  <div style={{ fontSize: '13.5px', fontWeight: 700, color: '#0F172A', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Layers size={16} color="#2563EB" /> Curriculum Modules ({modules.length})
                  </div>
                  <button
                    type="button"
                    onClick={() => {
                      const nextId = modules.length + 1;
                      setModules([...modules, { id: nextId, title: `Module ${nextId}: Advanced Application`, duration: '2 Hours', description: 'Advanced workflows and assessments.' }]);
                    }}
                    style={{ fontSize: '12px', color: '#2563EB', fontWeight: 600, background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                  >
                    <Plus size={13} /> Add Module
                  </button>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {modules.map((m, idx) => (
                    <div key={m.id || idx} style={{ backgroundColor: '#FFFFFF', border: '1px solid #E2E8F0', borderRadius: '8px', padding: '12px', display: 'flex', gap: '10px', alignItems: 'flex-start' }}>
                      <div style={{ width: '24px', height: '24px', borderRadius: '50%', backgroundColor: '#EFF6FF', color: '#2563EB', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', fontWeight: 700, flexShrink: 0, marginTop: '2px' }}>
                        {idx + 1}
                      </div>
                      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        <div style={{ display: 'flex', gap: '8px' }}>
                          <input
                            type="text"
                            placeholder="Module Title"
                            value={m.title}
                            onChange={(e) => {
                              const copy = [...modules];
                              copy[idx].title = e.target.value;
                              setModules(copy);
                            }}
                            style={{ flex: 1, padding: '6px 10px', borderRadius: '6px', border: '1px solid #CBD5E1', fontSize: '13px' }}
                          />
                          <input
                            type="text"
                            placeholder="Duration (e.g. 2 Hours)"
                            value={m.duration || ''}
                            onChange={(e) => {
                              const copy = [...modules];
                              copy[idx].duration = e.target.value;
                              setModules(copy);
                            }}
                            style={{ width: '130px', padding: '6px 10px', borderRadius: '6px', border: '1px solid #CBD5E1', fontSize: '13px' }}
                          />
                        </div>
                        <input
                          type="text"
                          placeholder="Brief description / Key topics"
                          value={m.description || ''}
                          onChange={(e) => {
                            const copy = [...modules];
                            copy[idx].description = e.target.value;
                            setModules(copy);
                          }}
                          style={{ width: '100%', padding: '6px 10px', borderRadius: '6px', border: '1px solid #CBD5E1', fontSize: '12.5px' }}
                        />
                      </div>
                      {modules.length > 1 && (
                        <button
                          type="button"
                          onClick={() => setModules(modules.filter((_, i) => i !== idx))}
                          style={{ color: '#EF4444', background: 'none', border: 'none', cursor: 'pointer', padding: '4px' }}
                        >
                          <X size={15} />
                        </button>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Automated Certificate & Dispatch Toggle */}
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '14px 18px',
                  backgroundColor: '#EFF6FF',
                  borderRadius: '10px',
                  border: '1px solid #BFDBFE',
                }}
              >
                <div>
                  <div style={{ fontSize: '13.5px', fontWeight: 700, color: '#1E293B', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <ShieldCheck size={16} color="#2563EB" /> Auto-Issue & Email Verified Certificate
                  </div>
                  <div style={{ fontSize: '12px', color: '#64748B', marginTop: '2px' }}>
                    Automatically generates cryptographic certificate & emails student when they complete 100% of modules.
                  </div>
                </div>
                <input
                  type="checkbox"
                  checked={autoCertify}
                  onChange={(e) => setAutoCertify(e.target.checked)}
                  style={{ width: '18px', height: '18px', cursor: 'pointer', accentColor: '#2563EB' }}
                />
              </div>

              {/* Modal Actions */}
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', paddingTop: '10px' }}>
                <button type="button" onClick={() => setShowPublishModal(false)} className="btn btn-outline btn-sm">
                  Cancel
                </button>
                <button type="submit" disabled={submitting} className="btn btn-primary btn-sm" style={{ display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
                  <Send size={14} />
                  {submitting ? 'Publishing...' : isEditing ? 'Update Program' : 'Publish Program'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ─── Enrolled Cohort Roster Modal ─── */}
      {showRosterModal && activeProgram && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            backgroundColor: 'rgba(15, 23, 42, 0.65)',
            backdropFilter: 'blur(5px)',
            zIndex: 9999,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px',
          }}
          onClick={(e) => {
            if (e.target === e.currentTarget) setShowRosterModal(false);
          }}
        >
          <div
            style={{
              backgroundColor: '#FFFFFF',
              borderRadius: '16px',
              width: '100%',
              maxWidth: '820px',
              maxHeight: '90vh',
              boxShadow: '0 25px 60px -15px rgba(0, 0, 0, 0.3)',
              overflow: 'hidden',
              display: 'flex',
              flexDirection: 'column',
            }}
          >
            {/* Header */}
            <div
              style={{
                padding: '20px 24px',
                backgroundColor: '#F8FAFC',
                borderBottom: '1px solid #E2E8F0',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <div>
                <h3 style={{ margin: 0, fontSize: '17px', fontWeight: 800, color: '#0F172A' }}>
                  Participant Cohort: {activeProgram.title}
                </h3>
                <p style={{ margin: '3px 0 0', fontSize: '12.5px', color: '#64748B' }}>
                  {roster.length} Enrolled Students &bull; Real-time module progress & certificate registry
                </p>
              </div>
              <button
                onClick={() => setShowRosterModal(false)}
                style={{ background: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}
              >
                <X size={16} />
              </button>
            </div>

            {/* Content Roster Table */}
            <div style={{ padding: '20px 24px', overflowY: 'auto', flex: 1 }}>
              {loadingRoster ? (
                <LoadingSpinner message="Fetching cohort roster..." />
              ) : roster.length === 0 ? (
                <div style={{ padding: '36px 0', textAlign: 'center', color: '#64748B' }}>
                  <Users size={32} style={{ margin: '0 auto 8px', color: '#94A3B8' }} />
                  <p style={{ margin: 0, fontSize: '14px' }}>No students have enrolled in this program yet.</p>
                </div>
              ) : (
                <div className="table-responsive">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>Student Name</th>
                        <th>Institution / Dept</th>
                        <th>Progress</th>
                        <th>Status</th>
                        <th style={{ textAlign: 'right' }}>Certificate Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {roster.map((s) => (
                        <tr key={s.enrollment_id}>
                          <td>
                            <div style={{ fontWeight: 700, color: '#0F172A', fontSize: '13.5px' }}>{s.student_name}</div>
                            <div style={{ fontSize: '12px', color: '#64748B' }}>{s.student_email}</div>
                          </td>
                          <td style={{ fontSize: '12.5px', color: '#475569' }}>
                            <div>{s.student_institution || 'Independent Candidate'}</div>
                            <div style={{ fontSize: '11px', color: '#64748B' }}>{s.student_department || ''}</div>
                          </td>
                          <td style={{ width: '160px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                              <div style={{ flex: 1, height: '7px', backgroundColor: '#E2E8F0', borderRadius: '10px', overflow: 'hidden' }}>
                                <div
                                  style={{
                                    height: '100%',
                                    width: `${s.progress_percent}%`,
                                    backgroundColor: s.progress_percent >= 100 ? '#10B981' : '#2563EB',
                                    borderRadius: '10px',
                                  }}
                                />
                              </div>
                              <span style={{ fontSize: '12px', fontWeight: 700, color: '#0F172A' }}>
                                {s.progress_percent}%
                              </span>
                            </div>
                          </td>
                          <td>
                            <span
                              className={`badge ${
                                s.status === 'completed'
                                  ? 'badge-success'
                                  : s.status === 'in_progress'
                                  ? 'badge-info'
                                  : 'badge-neutral'
                              }`}
                            >
                              {s.status.replace('_', ' ')}
                            </span>
                          </td>
                          <td style={{ textAlign: 'right' }}>
                            {s.certificate_issued ? (
                              <button
                                onClick={() =>
                                  setPreviewCert({
                                    certificate_number: s.certificate_number,
                                    student_name: s.student_name,
                                    program_title: activeProgram.title,
                                    issuer_name: activeProgram.provider_name,
                                    issue_date: s.completed_at || new Date().toISOString(),
                                    verification_hash: s.verification_hash,
                                    skills: activeProgram.skills_covered,
                                  })
                                }
                                style={{
                                  display: 'inline-flex',
                                  alignItems: 'center',
                                  gap: '5px',
                                  padding: '5px 10px',
                                  backgroundColor: '#ECFDF5',
                                  color: '#047857',
                                  border: '1px solid #A7F3D0',
                                  borderRadius: '6px',
                                  fontSize: '11.5px',
                                  fontWeight: 700,
                                  cursor: 'pointer',
                                }}
                              >
                                <ShieldCheck size={13} /> View Cert (#{s.certificate_number?.substring(0, 12)})
                              </button>
                            ) : (
                              <button
                                onClick={() => handleIssueCertificate(s.enrollment_id)}
                                disabled={issuingCertId === s.enrollment_id}
                                style={{
                                  display: 'inline-flex',
                                  alignItems: 'center',
                                  gap: '5px',
                                  padding: '5px 12px',
                                  backgroundColor: '#2563EB',
                                  color: '#FFFFFF',
                                  border: 'none',
                                  borderRadius: '6px',
                                  fontSize: '11.5px',
                                  fontWeight: 600,
                                  cursor: issuingCertId === s.enrollment_id ? 'not-allowed' : 'pointer',
                                }}
                              >
                                <Award size={13} />
                                {issuingCertId === s.enrollment_id ? 'Dispatching...' : 'Issue & Email'}
                              </button>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Footer */}
            <div style={{ padding: '14px 24px', backgroundColor: '#F8FAFC', borderTop: '1px solid #E2E8F0', display: 'flex', justifyContent: 'flex-end' }}>
              <button onClick={() => setShowRosterModal(false)} className="btn btn-secondary btn-sm">
                Close Roster
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ─── Verified Certificate Viewer Modal ─── */}
      {previewCert && (
        <CertificateModal certificate={previewCert} onClose={() => setPreviewCert(null)} />
      )}
    </PortalLayout>
  );
}
